# Generated by Django 6.0.6 on 2026-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_fetched_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
