# Generated by Django 6.0.6 on 2026-06-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_datasource_last_fetched_date_datasource_raw_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='url_api',
            new_name='api_url',
        ),
    ]
